### ISSUE TITLE
Allow support for puppet-telegraf 4.0.0

### ISSUE THREAD

**Issue by thunderpants73** [puppetlabs/puppet_metrics_dashboard#158]
Currently the module only allows:

`puppet-telegraf (>= 2.0.0 < 4.0.0)`

In trying to upgrade the `puppet-telegraf` in our environment, we are unable due to the dependency of the `puppet_metrics_dashboard`.

**Comment by jarretlavallee** [comment]
Thank you for opening this issue @thunderpants73. Unfortunately, we cannot increase that version at the moment. `puppet-telegraf` 4.0.0 and 4.0.1 have a bug that is incompatible with this module. The bug has been fixed in the master branch with https://github.com/voxpupuli/puppet-telegraf/pull/160, but has not yet been released.

**Comment by jarretlavallee** [comment]
https://github.com/voxpupuli/puppet-telegraf/issues/173 was opened to ask for a release. You can likely use the 4.0.0 version of the module if you define a `Yumrepo[influxdata]` resource. Something like the following may work. 

```
yumrepo {'influxdata': ensure => absent }
include puppet_metrics_dashboard
```
